<a href="https://colab.research.google.com/github/The-Professor99/ML_Practice/blob/main/hands_on_learning/tinkerings/dim_reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I started looking into recommender systems and collaborative filtering in particular in which the input matrix of users-ratings is broken down into 3 matrices of user-features, features-features and item-features matrices using a technique called Singular Value Decomposition (SVD).
So, I set out learning and diving deeper into how SVD actually works and how these three matrices are formed a.k.a how is a given input matrix decomposed to these three matrices.

### Eigenvalues and Eigenvectors
A Vector is scaled and/or rotated when some linear transformation(matrix) is applied to it. Any vector that is only scaled by a matrix(but not rotated) is called an eigen vector and the corresponding scale factors are known as eigenvalues of matrix.

#### Eigenvalues of matrix
The eigenvalues of matrix are scalars by which some vectors(eigenvectors) change when the matrix(transformation) is applied to it.
In other words, if A is a square matrix of order n x n and v is a non-zero column vector of order n x 1 such that Av = λv(this means that the product of A and v is just a scalar multiple of v), then the scalar (real number) λ is called an eigenvalue of the matrix A that corresponds to the eigenvector v. The word "eigen" is german and means "characteristic", "proper" or "own". Thus, eigenvalues are also known as characteristic values or proper values.

#### How to Find Eigenvalues:
From the definition, if λ is an eigenvalue of a square matrix A, then
Av = λv ------ (1) \
If I is the identity matrix of the same order as A, then we can write the above equation as
Av = λ(Iv) (because v = Iv)
therefore
Av - λ(Iv) = 0
v(A - λI) = 0

This represents a homogeneous system of linear equations and it has a non-trivial solution only when the determinant of the coefficient matrix is 0.
i.e |A - λI| = 0
This equation is called the characteristic equation(where |A - λ| is called the characteristic polynomial) and by solving this for λ, we get the eigen values.
##### Step by step process to find the eigenvalues of a square matrix A.
- Take the identity matrix I whose order is the same as A.
- Multiply every element of I by λ to get λI.
- Subtract λI from A to get A - λI.
- Find it's determinant.
- Set the determinant to zero and solve for λ.

#### Examples
1. Finding the eigenvalues of a 2x2 matrix
   Say $$A =
        \left(\begin{array}{cc}
        5 & 4\\
        1 & 2
        \end{array}\right)
        $$
   Let λ represent it's eigenvalue(s). The Identity matrix of order 2x2 is
   $$I =
        \left(\begin{array}{cc}
        1 & 0\\
        0 & 1
        \end{array}\right)
        $$
   Then $$λI =  λ
        \left(\begin{array}{cc}
        1 & 0\\
        0 & 1
        \end{array}\right)
         =
        \left(\begin{array}{cc}
        λ & 0\\
        0 & λ
        \end{array}\right)
         $$
   $$A - λI =
        \left(\begin{array}{cc}
        5 & 4\\
        1 & 2
        \end{array}\right)
        -
        \left(\begin{array}{cc}
        λ & 0\\
        0 & λ
        \end{array}\right)
        =
        \left(\begin{array}{cc}
        5-λ & 4\\
        1 & 2-λ
        \end{array}\right)
        $$
   Its determinant is:
   |A - λI| = $(5-λ)(2-λ) - (1)(4) = 10 - 5λ - 2λ^2 + λ^2 - 4$
               $λ^2 - 7λ + 6$
   From Characteristic equation
   |A - λI| = 0, hence
   $λ^2 - 7λ + 6 = 0$
   solving quadratically,
   λ = 6, λ = 1
   Thus the eigenvalues of matrix A are 1 and 6.

2. Finding the eigen values of a 3x3 matrix.
   Say $$A =
        \left(\begin{array}{cc}
        3 & 1 & 1\\
        2 & 4 & 2\\
        1 & 1 & 3
        \end{array}\right)
        $$
   From above, we can observe that the result of A - λI is just the matrix obtained by subtracting λ from all diagonal elements of A.
   Hence, from |A - λI| = 0
   $$|\left(\begin{array}{cc}
        3 - λ & 1 & 1\\
        2 & 4 - λ & 2\\
        1 & 1 & 3 - λ
        \end{array}\right)| = 0
        $$

   $(3 - λ)[(4 - λ)(3 - λ) - 2(1) ] - 1 [ 2(3 - λ) - 2(1) ] + 1 [2 (1) - 1 (4 - λ) ] = 0 $

    $(3 - λ) [12 - 4λ - 3λ + λ^2 - 2] - 6 + 2λ + 2 + 2 - 4 + λ = 0$

    $(3 - λ) [10 - 7λ + λ^2] - 6 + 3λ = 0$

    $30 - 21λ + 3λ^2 - 10λ + 7λ^2 - λ^3 - 6 + 3λ = 0$

    $-λ^3 + 10λ^2 - 28λ + 24 = 0$
    Multiplying both sides by -1,
    
    λ3 - 10λ2 + 28λ - 24 = 0
   This is a cubic equation, solving, we get 2, 2 and 6(Eigen values of the matrix)

#### Properties of Eigenvalues   
- A square matrix of order n has at most n eigenvalues.
- An identity matrix has only one eigenvalue which is 1.
- The eigenvalues of triangular matrices and diagonal matrices are nothing but the elements of their principal diagonal.
- The sum of eigenvalues of matrix A is equal to the sum of its diagonal elements.
- The product of eigenvalues of matrix A is equal to its determinant.
- The eigenvalues of hermitian and symmetric matrices are real.
- The eigenvalues of skew hermitian and skew-symmetric matrices are either zeros are purely imaginary numbers.
- A matrix and its transpose have the same eigenvalues.
- If A and B are two square matrices of the same order, then AB and BA have the same eigenvalues.
- The eigenvalues of an orthogonal matrix are 1 and -1.
- If λ is an eigenvalue of A, then kλ is an eigenvalue of kA, where 'k' is a scalar.
- If λ is an eigenvalue of A, then λk is an eigenvalue of Ak.
- If λ is an eigenvalue of A, then 1/λ is an eigenvalue of A-1 (if the inverse of A exists).
- If λ is an eigenvalue of A, then |A| / λ is an eigenvalue of the adjoint of A.
Apart from these properties, we have another theorem related to eigenvalues called the "Caley-Hamilton Theorem". It says, "every square matrix satisfies its characteristic equation". i.e., if A is a square matrix then it satisfies |A - λI| = 0. For example, if λ2 - 8λ + 12 = 0 is the characteristic equation of a square matrix A, then A2 - 8A + 12 = 0.

Imaginary eigenvalues signify rotation, not scaling and negative real components correspond to decay. Positive real components signify growth or instability.
Eigenvectors and eigen values reveal long term behaviour.

Some Uses of EigenVectors and Eigenvalues:
- Singular value decomposition.
- Spectral Clustering.
- Dimensionality reduction/PCA.
- Low rank factorization for collaborative prediction.
- Google page rank algorithm.

when you transform a matrix by a vector and if the transformed vector is just the scaled version of the original one with no change in direction then this vector is called the Eigenvector.

https://www.youtube.com/watch?v=i8FukKfMKCI

### Singular Value Decomposition(SVD)

Singular Value Decomposition

SVD is a data/dimensionality reduction tool, eg, you have a high resolution image with big data, svd helps reduce this data into the key features that are necessary for analyzing, understanding and describing this data.
SVD is scalable hence can be applied to massive datasets, such as google's application(page rank) which is a lot of pages.
https://www.youtube.com/watch?v=nbBvuuNVfco

The Singular Value Decomposition(SVD) of a matrix is a factorization of that matrix into 3 matrices.

The SVD of an mxn matrix A is given by the formula $A = U\sum{V^T}$
where:
- A: is the input matrix
- U: are the left singular vectors
- $\sum$: are the diagonal/eigenvalues
- V are the right singular vectors

The shape of these three matrices will be
- A - m x n matrix
- U - m x k matrix
- $\sum$ - k x k matrix
- V - n x k matrix

Singular Value decomposition is the mathematics behind principal component analysis(in data analysis) and latent semantic analysis(in natural language processing). This operation transforms a dense matrix into a diagonal matrix. In linear algebra, diagonal matrices are very special and highly desirable. They behave like scalar numbers when we multiply by them, only stretching or squeezing in certain directions. Singular value decomposition can be applied to any matrix.

SVD is often used in a wide array of applications including compressing, denoising and data reduction. Every rectangular matrix has an SVD, although the resulting matrices may contain complex numbers and the limitations of floating point arithmetic may cause some matrices to fail to decompose neatly.

SVD is also used in the calculation of other matrix operations such as matrix inverse, and also as a data reduction method.

Properties of SVD
Orthogonality: The matrices
𝑈
U and
𝑉
V are orthogonal, meaning
𝑈
𝑇
𝑈
=
𝐼
U
T
 U=I and
𝑉
𝑇
𝑉
=
𝐼
V
T
 V=I, where
𝐼
I is the identity matrix.

Singular Values: The diagonal entries of
Σ
Σ (singular values) are non-negative and typically ordered in descending order. They represent the magnitude of the action of the matrix
𝐴

A in the directions specified by the corresponding singular vectors.

Dimensionality Reduction: SVD can be used for dimensionality reduction by keeping only the largest singular values and their corresponding singular vectors. This is the basis for Principal Component Analysis (PCA).

Applications of SVD
Data Compression: SVD can reduce the number of features in a dataset by representing the data with fewer dimensions while retaining most of the variance.

Image Compression: In image processing, SVD can be used to approximate images with fewer components, reducing storage requirements while maintaining visual quality.

Latent Semantic Analysis: In natural language processing, SVD helps in understanding the relationships between terms and documents by reducing the dimensionality of the term-document matrix.

Noise Reduction: By keeping only the largest singular values, SVD can filter out noise from data.

Solving Linear Systems: SVD is used to solve systems of linear equations, especially when the system is ill-conditioned or singular.

https://byjus.com/maths/singular-value-decomposition/
https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/
https://chatgpt.com/c/9d5e8b84-300f-4eeb-8ca0-a0aec806960a

In [ ]:
from numpy import array
from scipy.linalg import svd

A = array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
U, s, VT = svd(A)

In [ ]:
U

array([[-0.2298477 ,  0.88346102,  0.40824829],
       [-0.52474482,  0.24078249, -0.81649658],
       [-0.81964194, -0.40189603,  0.40824829]])

In [ ]:
s

array([9.52551809, 0.51430058])

In [ ]:
VT

array([[-0.61962948, -0.78489445],
       [-0.78489445,  0.61962948]])

### Dimensionality Reduction

What is the curse of dimensionality?
With the unprecedented growth of data collection and the revolution of Big data. The datasets that we would deal with will have extremely high dimensions. The dimensions could go up to thousands or more which makes it challenging to visualize and analyze each of the features.

Having such an enormous number of features can often lead to errors like overfitting in the models. It also makes it harder to design regression models as the weights can tend to be highly unstable due to multicollinearity arising from high dimensions. This problem is termed as the ‘Curse of the dimensionality’ where we see an increase of error with the exponential increase of features.

This is where the Dimensionality reduction techniques such as PCA or LDA come into play. They help in transforming the dataset of high dimensions into lower dimensions without having to lose the essence of the data.

### Principal Component Analysis (PCA)
Principal Component Analysis is an unsupervised dimension reduction technique that focuses on capturing maximum variation of the data.

Eigenvalues are scalar values that represent the magnitude of the variance explained by each principal component. They quantify the amount of information captured by a particular direction in the data. The corresponding eigenvectors are vectors that define those directions of maximum variance. In essence, eigenvectors are the new axes that represent the data most effectively.


Selecting the largest eigenvalues and their corresponding eigenvectors is crucial in PCA because they capture the most significant patterns in the data, reducing dimensionality while retaining most of the variability.

The Principal Component Analysis algorithm first identifies the hyperplane that lies closest to the data, and then it projects the data onto it. But before you can project the training set onto a lower dimensional hyperplane, you first need to choose the right hyperplane. It seems reasonable to select the axis that preserves the maximum amount of variance, as it will most likely lose less information than the other projections.(see page 220, Figure 8.7). This choice is the axis that minimizes the mean squared distance between the original dataset and its projection onto that axis or it is the axis that maximizes the mean squared distance between the origin and the projected points.

How does PCA achieve dimension reduction?
1.Principal Component analysis reduces high dimensions into low dimension subspace by creating a new set of components that carry most of the essential information of all the features.

2.These new components are a linear combination of all the features and the components thus formed are nothing but the eigenvectors which are now called the Principal components.

3.The eigenvalue corresponding to each of these eigenvectors will tell us about how much variation in the data has been captured by that particular Principal component.

4. Principal components are orthogonal to each other and are uncorrelated that increases maximum variance. As they are uncorrelated it solves the problem of multicollinearity.

Applications
The selection of the largest eigenvalues and eigenvectors in PCA is crucial for several reasons:

Dimensionality Reduction: The largest eigenvalues indicate the directions that capture the most significant amount of variance in the data. By selecting the corresponding eigenvectors (principal components), we can reduce the dimensionality of the data while retaining most of the information. This simplification is beneficial for visualization, computational efficiency, and noise reduction.
Feature Extraction: Eigenvectors associated with large eigenvalues represent the most important features in the data. These features are linear combinations of the original variables and often reveal underlying patterns or structures. Feature extraction through PCA is valuable in machine learning for building predictive models.
Noise Reduction: By focusing on the directions of maximum variance, PCA effectively filters out noise and irrelevant information present in the data. This noise reduction enhances the signal-to-noise ratio and improves the quality of subsequent analyses.

PCA assumes data is centered so we should always center data first or use some algorihtm which does. This can be done through standardization.
The aim of this step is to standardize the range of the continuous initial variables so that each one of them contributes equally to the analysis.

It is eigenvectors and eigenvalues who are behind all the magic of principal components because the eigenvectors of the Covariance matrix are actually the directions of the axes where there is the most variance (most information) and that we call Principal Components. And eigenvalues are simply the coefficients attached to eigenvectors, which give the amount of variance carried in each Principal Component.

More specifically, the reason why it is critical to perform standardization prior to PCA, is that the latter is quite sensitive regarding the variances of the initial variables. That is, if there are large differences between the ranges of initial variables, those variables with larger ranges will dominate over those with small ranges (for example, a variable that ranges between 0 and 100 will dominate over a variable that ranges between 0 and 1), which will lead to biased results. So, transforming the data to comparable scales can prevent this problem.

https://medium.com/@dareyadewumi650/understanding-the-role-of-eigenvectors-and-eigenvalues-in-pca-dimensionality-reduction-10186dad0c5c
https://builtin.com/data-science/step-step-explanation-principal-component-analysis

PCA is a general purpose dimensionality reduction technique that can be applied to any numerical data, including the embeddings produced by sentence transformers or BERT.