<a href="https://colab.research.google.com/github/The-Professor99/ML_Practice/blob/main/hands_on_learning/hands_on_ml_with_scikit-learn_Aurelien_textbook/Chapter_6_Decision_Trees_(Exercises).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
%matplotlib

Using matplotlib backend: TkAgg


In [ ]:
from sklearn.datasets import make_moons

In [ ]:
dataset = make_moons(n_samples=10000, noise=0.4)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dataset[0], dataset[1], test_size=0.1)

In [ ]:
def plot_dataset(X, y):
    if X.shape[1] == 1:
        plt.plot(X, y, "bs")
    else:
        plt.plot(X[:, 0][y==0], X[:, 1][y==0], "bs")
        plt.plot(X[:, 0][y==1], X[:, 1][y==1], "g^")
    plt.grid(True, which='both')
    plt.xlabel(r"$x_1$", fontsize=20)
    plt.ylabel(r"$x_2$", fontsize=20, rotation=0)

In [ ]:
plot_dataset(X_train, y_train)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
tree_clf = DecisionTreeClassifier(max_depth=2)

In [ ]:
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=2)

In [ ]:
from sklearn.tree import export_graphviz

In [ ]:
export_graphviz(tree_clf, out_file="images/exercise_tree.dot",
               class_names=["0", "1"], feature_names=["x1", "x2"])

In [ ]:
!dot -Tpng images/exercise_tree.dot -o images/exercise_tree.png

In [ ]:
plt.plot( [-3, 4], [0.231, 0.231], "k-", linewidth=2)
plt.plot( [-0.485, -0.485], [-2.5, 0.231], "r--", linewidth=2)
plt.plot( [1.506, 1.506], [0.231, 2.6], "b--", linewidth=2)


In [ ]:
y_pred = tree_clf.predict(X_train)

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score

In [ ]:
accuracy_score(y_train, y_pred)

0.85

In [ ]:
recall_score(y_train, y_pred)

0.8850166481687014

In [ ]:
precision_score(y_train, y_pred)

0.8273500726291761

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
scores = cross_val_score(tree_clf, X_train, y_train, cv=5)

In [ ]:
scores

array([0.83555556, 0.855     , 0.85055556, 0.83888889, 0.85611111])

In [ ]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [ ]:
param_grid = [
    {"max_depth": [2, 4, 6, 9, 15],
     "min_samples_split": [2, 40, 100, 500, 1000],
     "min_samples_leaf": [1, 5, 20, 30, 40],
     "max_leaf_nodes": [None, 10, 20, 30, 40, 50],
    }
]

In [ ]:
grid_search = GridSearchCV(tree_clf, param_grid, cv=5, return_train_score=True)

In [ ]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(max_depth=2),
             param_grid=[{'max_depth': [2, 4, 6, 9, 15],
                          'max_leaf_nodes': [None, 10, 20, 30, 40, 50],
                          'min_samples_leaf': [1, 5, 20, 30, 40],
                          'min_samples_split': [2, 40, 100, 500, 1000]}],
             return_train_score=True)

In [ ]:
grid_search.best_params_

{'max_depth': 9,
 'max_leaf_nodes': 20,
 'min_samples_leaf': 20,
 'min_samples_split': 2}

In [ ]:
cv_res = grid_search.cv_results_

In [ ]:
for score, params in zip(cv_res["mean_test_score"], cv_res["params"]):
    print(score, params)

0.8472222222222223 {'max_depth': 2, 'max_leaf_nodes': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
0.8472222222222223 {'max_depth': 2, 'max_leaf_nodes': None, 'min_samples_leaf': 1, 'min_samples_split': 40}
0.8472222222222223 {'max_depth': 2, 'max_leaf_nodes': None, 'min_samples_leaf': 1, 'min_samples_split': 100}
0.8472222222222223 {'max_depth': 2, 'max_leaf_nodes': None, 'min_samples_leaf': 1, 'min_samples_split': 500}
0.8472222222222223 {'max_depth': 2, 'max_leaf_nodes': None, 'min_samples_leaf': 1, 'min_samples_split': 1000}
0.8472222222222223 {'max_depth': 2, 'max_leaf_nodes': None, 'min_samples_leaf': 5, 'min_samples_split': 2}
0.8472222222222223 {'max_depth': 2, 'max_leaf_nodes': None, 'min_samples_leaf': 5, 'min_samples_split': 40}
0.8472222222222223 {'max_depth': 2, 'max_leaf_nodes': None, 'min_samples_leaf': 5, 'min_samples_split': 100}
0.8472222222222223 {'max_depth': 2, 'max_leaf_nodes': None, 'min_samples_leaf': 5, 'min_samples_split': 500}
0.8472222222222223 {'max

In [ ]:
final_clf = grid_search.best_estimator_

### Evaluating on a test set

In [ ]:
test_pred = final_clf.predict(X_test)

In [ ]:
accuracy_score(y_test, test_pred)

0.869

In [ ]:
precision_score(y_test, test_pred)

0.85546875

In [ ]:
recall_score(y_test, test_pred)

0.8848484848484849

### Exercise 2

In [ ]:
from sklearn.model_selection import ShuffleSplit, StratifiedShuffleSplit

In [ ]:
splits = ShuffleSplit(n_splits=10, test_size=)

In [ ]:
n_trees = 1000
n_instances = 100

subsets = []
split = ShuffleSplit(n_splits=1000, test_size=len(X_train) - n_instances)
for train_index, test_index in split.split(X_train, y_train):
    shuffle_train_set = X_train[train_index]
    shuffle_test_set = y_train[train_index]
    subsets.append((shuffle_train_set, shuffle_test_set))

In [ ]:
np.c_[subsets[0][0], subsets[0][1]]

array([[ 2.09798291,  0.44468083,  1.        ],
       [ 0.39915795,  1.01408481,  0.        ],
       [ 0.10682089,  1.13110054,  0.        ],
       [-0.38395292,  0.71934639,  0.        ],
       [ 1.44770989,  0.09267123,  0.        ],
       [ 1.33123521, -1.01139449,  1.        ],
       [ 0.01504496, -0.81357586,  1.        ],
       [ 0.30742151, -0.02052282,  0.        ],
       [ 0.30064811,  0.1651977 ,  1.        ],
       [-0.4880213 ,  0.10111478,  1.        ],
       [-1.32922086,  1.01885506,  0.        ],
       [-1.36710569,  1.61577853,  0.        ],
       [ 0.33584539, -0.18424848,  0.        ],
       [ 0.37575112,  1.51705304,  0.        ],
       [ 1.08582632,  0.18017598,  0.        ],
       [ 0.00315854,  0.80127755,  0.        ],
       [ 1.47268713, -0.88128963,  1.        ],
       [ 0.78428107,  0.35044208,  0.        ],
       [ 0.98252485,  0.04686771,  1.        ],
       [ 0.93708365, -0.18283026,  1.        ],
       [-1.2456635 ,  0.79270396,  0.   

In [ ]:
plot_dataset(subsets[10][0], subsets[10][1])

In [ ]:
from sklearn.base import clone

In [ ]:
forest = [clone(final_clf) for _ in range(n_trees)]

In [ ]:
accuracy_scores = []
for tree, (X_mini_train, y_mini_train) in zip(forest, subsets):
    tree.fit(X_mini_train, y_mini_train)

    y_pred = tree.predict(X_test)
    accuracy_scores.append(accuracy_score(y_test, y_pred))


In [ ]:
np.mean(accuracy_scores)

0.779783

In [ ]:
predictions = np.empty([n_trees, len(X_test)], dtype=np.uint8)
predictions

array([[192,  13, 144, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ...,
       [  1,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [ ]:

for tree_index, tree in enumerate(forest):
    predictions[tree_index] = tree.predict(X_test)

In [ ]:
predictions

array([[0, 1, 1, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 1, 1, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
predictions = np.empty([n_trees, len(X_test)], dtype=np.uint8)

for tree_index, tree in enumerate(forest):
    Y_pred[tree_index] = tree.predict(X_test)

In [ ]:
import scipy as sp

In [ ]:
y_pred_majority_votes, n_votes  = sp.stats.mode(predictions, axis=0)

/tmp/ipykernel_3581/808096923.py:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  y_pred_majority_votes, n_votes  = sp.stats.mode(predictions, axis=0)


In [ ]:
y_pred_majority_votes.reshape([-1])

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,

In [ ]:
accuracy_score(y_test,  y_pred_majority_votes.reshape([-1]))

0.804