<a href="https://colab.research.google.com/github/The-Professor99/ML_Practice/blob/main/hands_on_learning/hands_on_ml_with_scikit-learn_Aurelien_textbook/Chap_12_Custom_Models_and_Training_with_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

### Tensors and Operations

In [ ]:
# create a tensor with tf.constant(). The tensor represents
# a matrix with two rows and three columns of floats
tm = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
# a tensor representing a scalar
ts = tf.constant(42)

In [ ]:
tm + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [ ]:
# as tensor values created with tf.constant are constant
# and therefore, immutable, parameters that need to change
# over time are created using tf.Variable
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])

In [ ]:
# tf.variables can be modified in place using the assign
# method (or assign_add() or assign_sub() which increment
# or decrement the variable by the given value)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

## Customizing Models and Training Algorithms
### Custom Loss Function